options = {
    "url" : None,
    "wordlist" : None,
    "_wordlist" : [],
    "extensions" : (),
    "exclude_extensions" : (),
    "remove_extensions" : False,
    "force_extension": False,
    "lowercase" : False,
    "uppercase": False,
    "capitalization": False,
    "threads":25,
    "include_code": set(),
    "exclude_code": set(),
    "method" : "get",
    "retries": 3,
    "user_agent": "",
    "cookie": "",
    "timeout": 7.5,
    "max_rate": 0,
    "delay" : 0,  
    "allow_redirect" : False,
    "output" : None,

    "domain": None,
    "dns" : True,
    "subdomain" : False,
    "include_records" : (),
    "exclude_records" : set(),
    "default_path" : set(),
    "complete" : False,
    "wordlist_dns" : None,
    "_wordlist_dns" : [],
    "output_sub" : None
}

